--- 
- 
  hosts: all
  become: true
  tasks: 
    - 
      apt: "name=nodejs state=present"
      name: "Install Node.js"
    - 
      apt: "name=git state=present"
      name: "Install git"
    - 
      apt: "name=npm state=present"
      name: "Install npm (Node.js package manager)"
    - 
      apt: 
        deb: "https://packages.timber.io/vector/0.6.0/vector-amd64.deb"
        force: true
      name: "Install vector"
    - 
      apt: "name=npm state=present"
      name: "Install npm (Node.js package manager)"
    - 
      name: "start vector"
      systemd: 
        daemon_reload: true
        enabled: true
        name: vector
        state: restarted

